name: Compilar AutoLogin
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar CMake 32 bits
      run: cmake -B build -A Win32 -DCMAKE_BUILD_TYPE=Release

    - name: Compilar
      run: cmake --build build --config Release

    - name: Salvar DLL pra baixar
      uses: actions/upload-artifact@v4
      with:
        name: AutoLogin_DLL
        path: build/Release/*.dll
